@WebApplication1_HostAddress = http://localhost:5100

POST {{WebApplication1_HostAddress}}/api/TodoItems
Content-Type: application/json

{
  "name": "Firs t",
  "isComplete": false
}

###

GET {{WebApplication1_HostAddress}}/api/TodoItems/
Accept: application/json

###

@id=1
GET {{WebApplication1_HostAddress}}/api/TodoItems/{{id}}

###

PUT {{WebApplication1_HostAddress}}/api/TodoItems/{{id}}
Content-Type: application/json

{
    "id": {{id}},
    "isComplete": true
}

###

DELETE {{WebApplication1_HostAddress}}/api/TodoItems/{{id}}